from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('autenticar/', views.iniciar_sesion),
    path('cambiar_contrasenna/', views.cambiar_password, name='cambiar_pass'),
    path('solicitud/crear/', views.crear_solicitud, name='crear_solicitud'),
    path('desconectar/', views.desconectar, name='desconectar'),
    path('administrar/roles/', views.administrar_roles, name='admin_roles'),
    path('administrar/usuarios/', views.administrar_user, name='admin_user'),
    path('administrar/roles/eliminar/<str:nombre>/', views.eliminar_rol, name='eliminar_rol'),
    path('administrar/roles/permisos/<str:nombre>/', views.permisos_roles, name='permisos_roles'),
    path('administrar/roles/eliminar/<str:rol>/<str:permiso>/', views.eliminar_permiso_rol, name='eliminar_permiso_rol'),
    path('administrar/usuarios/nuevo/', views.crear_usuario, name='crear_usuario'),
    path('administrar/usuarios/editar/<int:id>/', views.editar_usuario, name='editar_usuario'),
    path('administrar/permisos/', views.view_permisos, name='view_permisos'),
    path('administrar/permisos/crear/', views.crear_permisos, name='crear_permisos'),
    path('administrar/permisos/eliminar/<str:codename>/', views.eliminar_permiso, name='eliminar_permisos'),
    path('solicitudes/listar/', views.view_solicitudes, name='view_solicitudes'),
    path('solicitud/aceptar/<int:id>/', views.aceptar_solicitud, name='aceptar_solicitud'),
    path('solicitud/denegar/<int:id>/', views.denegar_solicitud, name='denegar_solicitud'),
    path('doctores/', views.view_doctor, name='view_doctores'),
    path('doctores/crear/', views.crear_doctor, name='crear_doctores'),
    path('doctores/editar/<int:id>/', views.editar_doctor, name='editar_doctores'),
    path('doctores/eliminar/<int:id>/', views.eliminar_doctor, name='eliminar_doctores'),
    path('doctorandos/', views.view_doctorandos, name='view_doctorandos'),
    path('doctorandos/agregar/', views.nuevo_doctorando, name='crear_doctorandos'),
    path('doctorandos/eliminar/<int:id>/', views.eliminar_doctorando, name='eliminar_doctorando'),
    path('doctorandos/editar/<int:id>/', views.editar_doctorando, name='editar_doctorando'),
    path('usuario/eliminar/<int:id>/', views.eliminar_usuario_desde_admin, name='eliminar_usuario'),
    path('generar_reporte/', views.generar_reporte, name='generar_reporte'),
    path('generar_reporte/solicitantes/<str:fechaI>/<str:fechaF>/', views.generar_reporte_solicitantes, name='generar_reporte_solicitantes'),
    path('generar_reporte/doctorando/<str:fechaI>/<str:fechaF>/<str:tesis>/', views.generar_reporte_doctorando, name='generar_reporte_doctorando'),
    path('generar_reporte/doctor/<str:fechaI>/<str:fechaF>/<str:areaPosgrado>/', views.generar_reporte_doctor, name='generar_reporte_doctor'),
]
